language: python
python:
  - "3.5"
cache: pip
services:
  - docker
  
install:
  - pip install -r requirements.txt
  - ./start_kafk.sh
script:
  - coverage run tests/fb_posts_test.py
after_success:
  - codecov